#!/usr/bin/env php
<?php

/**
 * This file is part of the LJS project.
 *
 * @author Vladislav Gritsenko (Inlife)
 * @link https://github.com/Inlife/ljs
 * 
 * @copyright 
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

if (PHP_VERSION < "5.3.0") {
    print("[ljs] Error: PHP 5 >= 5.3.0 is needed!\n");
    exit(1);
}

if (count($argv) < 2) {
    print("Usage: $ php ljs filename [pattern [outputfile]]\n");
    exit(1);
}

if (!file_exists($argv[1])) {
    print("[ljs] Error: file (" . $argv[1] . ") is not found!\n");
    exit(1);
}

if (isset($argv[2]) && !file_exists($argv[2])) {
    print("[ljs] Error: pattern file (" . $argv[1] . ") is not found!\n");
    exit(1);
}

class LJS {

    private $rules;
    private $files;


    /**
     * Create object, pass arguments
     * @param array[string] $arguments 
     */
    public function __construct($arguments)
    {
        $this->files = array(
            "input"  => pathinfo($arguments[1]),
            "pattern" => @$arguments[2],
            "output" => @$arguments[3]
        );

        $this->rules = array(
            "static"  => array(),
            "dynamic" => array(
                "/import\((?:\'|\\\")([A-Za-z0-9\/\.]+)(?:\'|\\\")\)[\;]?/" => function($m) {
                    $filename = $this->files["input"]["dirname"] . DIRECTORY_SEPARATOR . $m[1];
                    if (file_exists($filename)) {
                        return $this->parse( file_get_contents($filename) );
                    } else {
                        print("[ljs] Error: imporing file (" . $filename . ") doesn't exists.\n");
                        return "-- include(".$m[1].") - file not found.";
                    }
                },
                "/\#define([\W\w]{1,128}?)\#def_as([\W\w]{1,256}?)\#end_def\R/" => function($m) {
                    $this->addRule(
                        $this->createCondition($m[1]),
                        trim($m[2])
                    );
                },
                "/\#compress\s+((?:true|false))/i" => function($m) {
                    if ($m[1] === "true") {
                        $this->addRule("/\s+/", " ");
                    }
                }
            )
        );

        if (isset($this->files['pattern'])) {
            return $this->parse( file_get_contents($this->files['pattern']) );
        }
    }

    /**
     * Register action|value to insert|call on matching regex pattern
     * @param string $pattern Regex pattern to register
     * @param string|object-closure $replacement String that will be inserted on match, or closure that will be called
     * @return object $this
     */
    public function addRule($pattern, $replacement)
    {
        if (gettype($replacement) === "string") {

            $this->rules["static"][$pattern] = $replacement;

        } else if (gettype($replacement) === "object" && get_class($replacement) === "Closure") {

            $this->rules["dynamic"][$pattern] = $replacement;

        }

        return $this;
    }

    /**
     * When parsed from regex pattern from a file, we need to convert data
     * @param string $data
     * @return string
     */
    private function createCondition($data)
    {
        $data = trim($data);
        $data = addslashes($data);
        $symbols = "[](){}";
        for ($i = 0; $i < strlen($symbols); $i++) {
            $data = str_replace($symbols[$i], "\\".($symbols[$i]), $data);
        }
        $data = str_replace(" ", "\s+", $data);
        $data = str_replace("??", "([A-Za-z0-9\\\"\'\ _,]*)", $data);
        $data = str_replace("?", "([A-Za-z0-9\\\"\'_]+)", $data);
        $data = "/$data/";

        return $data;
    }

    /**
     * Parsing file text data
     * @param string $content
     * @return string
     */
    private function parse($content)
    {
        foreach($this->rules["dynamic"] as $pattern => $replacement)
        {
            $count = 0;

            if ( preg_match($pattern, $content) ) {
                $content = preg_replace_callback($pattern, $replacement, $content, -1, $count);
                //printf("[luamac] Pattern #%d applied $count times.\n", $i);
            }
        }

        foreach($this->rules["static"] as $pattern => $replacement)
        {
            $count = 0;

            if ( preg_match($pattern, $content) ) {
                $content = preg_replace($pattern, $replacement, $content, -1, $count);
                //printf("[luamac] Pattern #%d applied $count times.\n", $i);
            }
        }

        return $content;
    }

    /**
     * Start execution, load, parse and save file
     */
    public function start()
    {
        $started = microtime(); 

        $this->save(
            $this->parse( $this->load() )
        );

        printf("[ljs] Compiled in %.3fms.\n", (microtime() - $started));
    }

    /**
     * Load input file from our input arrays
     * @return string
     */
    private function load()
    {
        return file_get_contents($this->files["input"]["dirname"] . DIRECTORY_SEPARATOR . $this->files["input"]["basename"]);
    }

    /**
     * Save data to file
     * @param string $data Text data of parsed and processed input file
     * @return boolean (true) save succeeded 
     */
    private function save($data)
    {
        $data = "-- Compiled in LJS v0.1. \n-- https://github.com/Inlife/ljs \n" . $data;
        
        if ($this->files["output"] && strlen($this->files["output"]) > 0) {
            file_put_contents($this->files["input"]["dirname"] . DIRECTORY_SEPARATOR . $this->files["output"], $data);
        } else {
            file_put_contents($this->files["input"]["dirname"] . DIRECTORY_SEPARATOR . $this->files["input"]["filename"] . $this->getExtension(), $data);
        }

        return true;
    }

    /**
     * Extension which must be applied to file we are saving right now
     * @return string
     */
    private function getExtension() {
        if ($this->files["input"]["extension"] === "ljs") {
            return ".lua";
        }
        
        return ".ljs";
    }
}

// Create instance
$ljs = new LJS($argv);

// Register rules
$ljs->addRule("/LJS/", function() {
    return "-- LJS: Version 0.1;";
});

// Parse file
$ljs->start();